### ISSUE TITLE
How to backup settings?

### ISSUE THREAD

**Issue by oh6kw** [0xAF/openwebrxplus-softmbe-docker#5]
At first start owrx reads settings from docker volume owrxp-settings.
Where it stores settings when running?  How can i backup settings?

**Comment by 0xAF** [comment]
Either use this or similar method: https://www.howtogeek.com/devops/how-to-back-up-your-docker-volumes/

Or don't use volumes. I personally prefer to use local folders instead of volumes.
https://www.freecodecamp.org/news/docker-mount-volume-guide-how-to-mount-a-local-directory/

And last but not least, learn your tools. If you're going to use Docker container, learn how to do it. Everything is out there, in the search engines like Google.

Good luck.

(repoen this issue, if you have questions related to the container itself, not a general questions on how to use docker.)
